name: build-website

on:
  workflow_call:

jobs:
  build:
    name: Build application and database
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Build publishable website
      run: |
        cd ./src/ToyCompany/ToyCompany.Website
        dotnet restore

    - name: Publish website as workflow artifact
      uses: actions/upload-artifact@v2
      with:
        name: todo
        path: ./src/ToyCompany
