name: build-website

on:
  workflow_call:

jobs:
  build:
    name: Build application and database
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Build publishable website
      run: |
        dotnet publish --configuration Release -p PackageAsSingleFile=true
        zip -r publish.zip bin/Release/netcoreapp3.1/publish
      working-directory: ./src/ToyCompany/ToyCompany.Website/bin/Release/netcoreapp3.1/

    - name: Publish website as workflow artifact
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: ./src/ToyCompany/ToyCompany.Website/bin/Release/netcoreapp3.1/publish.zip
