name: learn-github-actions

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
#  build:
#    uses: johndowns/test-workflow-1/.github/workflows/build.yml@main

#  lint:
#    uses: johndowns/test-workflow-1/.github/workflows/lint.yml@main

  deploy-test:
    uses: johndowns/test-workflow-1/.github/workflows/deploy.yml@main
    with:
      environmentType: Test
      resourceGroupName: abc
    secrets:
      mysecret: ${{ secrets.mysecret }}

  deploy-production:
    uses: johndowns/test-workflow-1/.github/workflows/deploy.yml@main
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: def
    secrets:
      mysecret: ${{ secrets.mysecret }}
