name: learn-github-actions

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    uses: johndowns/test-workflow-1/.github/workflows/build.yml@main

  lint:
    uses: johndowns/test-workflow-1/.github/workflows/lint.yml@main