name: learn-github-actions

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    uses: johndowns/test-workflow-1/.github/workflows/build.yml@main

  lint:
    uses: johndowns/test-workflow-1/.github/workflows/lint.yml@main

  deploy-test:
    uses: johndowns/test-workflow-1/.github/workflows/deploy.yml@main
    needs: [build, lint]
    with:
      environmentType: Test
      resourceGroupName: ToyWeb2Test
      reviewApiUrl: TODO
      sqlServerAdministratorLogin: testsqladmin
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      reviewApiKey: TODO
      sqlServerAdministratorLoginPassword: 'Test123!!!!!' # TODO bad

  deploy-production:
    uses: johndowns/test-workflow-1/.github/workflows/deploy.yml@main
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: ToyWeb2Production
      reviewApiUrl: TODO
      sqlServerAdministratorLogin: prodsqladmin
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      reviewApiKey: TODO
      sqlServerAdministratorLoginPassword: Test123!!!!!
