name: learn-github-actions

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME_Test: abc
  AZURE_RESOURCEGROUP_NAME_Production: def

jobs:
#  build:
#    uses: johndowns/test-workflow-1/.github/workflows/build.yml@main

#  lint:
#    uses: johndowns/test-workflow-1/.github/workflows/lint.yml@main

  deploy-test:
    uses: johndowns/test-workflow-1/.github/workflows/deploy.yml@main
    with:
      environmentType: Test

  deploy-production:
    uses: johndowns/test-workflow-1/.github/workflows/deploy.yml@main
    needs: deploy-test
    with:
      environmentType: Production
